import { type Product, type Category, type Service } from "@/types";

export const mockProducts: Product[] = [
  {
    id: "1",
    slug: "netflix-premium-1-thang",
    name: "Netflix Premium 1 tháng",
    description: "Tài khoản Netflix Premium chất lượng cao, có thể xem trên 4 thiết bị cùng lúc, độ phân giải 4K.",
    price: 49000,
    originalPrice: 79000,
    category: { id: "1", name: "Netflix", slug: "netflix", icon: "🎬", productCount: 128, createdAt: new Date() } as Category,
    thumbnail: "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=400&h=400&fit=crop",
    images: [],
    stock: 128,
    rating: 4.9,
    sold: 15420,
    warranty: "1 tháng",
    badge: "BEST_SELLER",
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    slug: "spotify-premium-1-nam",
    name: "Spotify Premium 1 năm",
    description: "Tài khoản Spotify Premium, nghe nhạc không quảng cáo, tải offline, chất lượng cao 320kbps.",
    price: 79000,
    originalPrice: 120000,
    category: { id: "2", name: "Spotify", slug: "spotify", icon: "🎵", productCount: 85, createdAt: new Date() } as Category,
    thumbnail: "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=400&fit=crop",
    images: [],
    stock: 85,
    rating: 4.8,
    sold: 9850,
    warranty: "1 năm",
    badge: "HOT",
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    slug: "canva-pro-1-nam",
    name: "Canva Pro 1 năm",
    description: "Tài khoản Canva Pro với đầy đủ tính năng thiết kế, thư viện template khổng lồ.",
    price: 39000,
    category: { id: "3", name: "Canva", slug: "canva", icon: "🎨", productCount: 64, createdAt: new Date() } as Category,
    thumbnail: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=400&fit=crop",
    images: [],
    stock: 64,
    rating: 4.7,
    sold: 7230,
    warranty: "1 năm",
    badge: "BEST_SELLER",
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    slug: "youtube-premium-6-thang",
    name: "YouTube Premium 6 tháng",
    description: "Tài khoản YouTube Premium - xem video không quảng cáo, tải offline, phát nền.",
    price: 89000,
    originalPrice: 149000,
    category: { id: "4", name: "YouTube", slug: "youtube", icon: "▶️", productCount: 42, createdAt: new Date() } as Category,
    thumbnail: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=400&h=400&fit=crop",
    images: [],
    stock: 42,
    rating: 4.8,
    sold: 5620,
    warranty: "6 tháng",
    badge: "PREMIUM",
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5",
    slug: "disney-premium-1-thang",
    name: "Disney+ Premium 1 tháng",
    description: "Tài khoản Disney+ Premium, xem phim Marvel, Star Wars, Pixar và nhiều hơn.",
    price: 35000,
    category: { id: "5", name: "Disney+", slug: "disney", icon: "🏰", productCount: 38, createdAt: new Date() } as Category,
    thumbnail: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&h=400&fit=crop",
    images: [],
    stock: 38,
    rating: 4.6,
    sold: 3210,
    warranty: "1 tháng",
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6",
    slug: "discord-nitro-1-thang",
    name: "Discord Nitro 1 tháng",
    description: "Tài khoản Discord Nitro - avatar animated, emoji tùy chỉnh, upload 100MB.",
    price: 45000,
    category: { id: "6", name: "Discord", slug: "discord", icon: "🎮", productCount: 25, createdAt: new Date() } as Category,
    thumbnail: "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400&h=400&fit=crop",
    images: [],
    stock: 25,
    rating: 4.5,
    sold: 2100,
    warranty: "1 tháng",
    badge: "NEW",
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "7",
    slug: "chatgpt-plus-1-thang",
    name: "ChatGPT Plus 1 tháng",
    description: "Tài khoản ChatGPT Plus - truy cập GPT-4, DALL-E, Browsing, Plugin.",
    price: 150000,
    originalPrice: 200000,
    category: { id: "7", name: "ChatGPT", slug: "chatgpt", icon: "🤖", productCount: 30, createdAt: new Date() } as Category,
    thumbnail: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=400&fit=crop",
    images: [],
    stock: 30,
    rating: 4.9,
    sold: 4500,
    warranty: "1 tháng",
    badge: "HOT",
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "8",
    slug: "capcut-pro-1-nam",
    name: "CapCut Pro 1 năm",
    description: "Tài khoản CapCut Pro - công cụ chỉnh sửa video chuyên nghiệp, hiệu ứng cao cấp.",
    price: 55000,
    category: { id: "8", name: "CapCut", slug: "capcut", icon: "✂️", productCount: 20, createdAt: new Date() } as Category,
    thumbnail: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=400&h=400&fit=crop",
    images: [],
    stock: 20,
    rating: 4.7,
    sold: 1890,
    warranty: "1 năm",
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "9",
    slug: "facebook-via-uid-vietnam",
    name: "Facebook VIA UID Vietnam",
    description: "Tài khoản Facebook VIA (真实) - tài khoản thật, hoạt động tốt, có bảo hành.",
    price: 150000,
    originalPrice: 200000,
    category: { id: "9", name: "Facebook", slug: "facebook", icon: "📘", productCount: 45, createdAt: new Date() } as Category,
    thumbnail: "https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=400&h=400&fit=crop",
    images: [],
    stock: 45,
    rating: 4.4,
    sold: 3200,
    warranty: "Bảo hành",
    badge: "HOT",
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "10",
    slug: "locket-gold-1-thang",
    name: "Locket Gold 1 tháng",
    description: "Tài khoản Locket Gold - xem ảnh của bạn bè trên màn hình widget.",
    price: 25000,
    category: { id: "10", name: "Locket", slug: "locket", icon: "💎", productCount: 15, createdAt: new Date() } as Category,
    thumbnail: "https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=400&h=400&fit=crop",
    images: [],
    stock: 15,
    rating: 4.6,
    sold: 890,
    warranty: "1 tháng",
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "11",
    slug: "tiktok-ads-1-thang",
    name: "TikTok Ads 1 tháng",
    description: "Tài khoản TikTok Ads - chạy quảng cáo TikTok, tiếp cận hàng triệu người dùng.",
    price: 250000,
    category: { id: "11", name: "TikTok", slug: "tiktok", icon: "🎵", productCount: 12, createdAt: new Date() } as Category,
    thumbnail: "https://images.unsplash.com/photo-1611605698335-8b1569810432?w=400&h=400&fit=crop",
    images: [],
    stock: 12,
    rating: 4.5,
    sold: 650,
    warranty: "1 tháng",
    badge: "PREMIUM",
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "12",
    slug: "facebook-bm-agency",
    name: "Facebook BM Agency",
    description: "Tài khoản Business Manager (BM) Agency - quản lý nhiều Fanpage, chạy ads hiệu quả.",
    price: 350000,
    originalPrice: 500000,
    category: { id: "9", name: "Facebook", slug: "facebook", icon: "📘", productCount: 45, createdAt: new Date() } as Category,
    thumbnail: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=400&h=400&fit=crop",
    images: [],
    stock: 8,
    rating: 4.7,
    sold: 450,
    warranty: "Bảo hành dài hạn",
    badge: "BEST_SELLER",
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockCategories: Category[] = [
  { id: "1", name: "Netflix", slug: "netflix", icon: "🎬", productCount: 128, color: "linear-gradient(135deg, #E50914, #B81D24)", fromPrice: 49000, createdAt: new Date() },
  { id: "2", name: "Spotify", slug: "spotify", icon: "🎵", productCount: 85, color: "linear-gradient(135deg, #1DB954, #1ED760)", fromPrice: 79000, createdAt: new Date() },
  { id: "3", name: "Canva", slug: "canva", icon: "🎨", productCount: 64, color: "linear-gradient(135deg, #00C4CC, #7D2AE8)", fromPrice: 39000, createdAt: new Date() },
  { id: "4", name: "YouTube", slug: "youtube", icon: "▶️", productCount: 42, color: "linear-gradient(135deg, #FF0000, #CC0000)", fromPrice: 89000, createdAt: new Date() },
  { id: "5", name: "Disney+", slug: "disney", icon: "🏰", productCount: 38, color: "linear-gradient(135deg, #113CCF, #0070C9)", fromPrice: 35000, createdAt: new Date() },
  { id: "6", name: "Discord", slug: "discord", icon: "🎮", productCount: 25, color: "linear-gradient(135deg, #5865F2, #4752C4)", fromPrice: 45000, createdAt: new Date() },
  { id: "7", name: "ChatGPT", slug: "chatgpt", icon: "🤖", productCount: 30, color: "linear-gradient(135deg, #10A37F, #74AA9C)", fromPrice: 150000, createdAt: new Date() },
  { id: "8", name: "CapCut", slug: "capcut", icon: "✂️", productCount: 20, color: "linear-gradient(135deg, #00D2FF, #3A7BD5)", fromPrice: 55000, createdAt: new Date() },
  { id: "9", name: "Facebook", slug: "facebook", icon: "📘", productCount: 45, color: "linear-gradient(135deg, #1877F2, #0D8BD9)", fromPrice: 150000, createdAt: new Date() },
  { id: "10", name: "Locket", slug: "locket", icon: "💎", productCount: 15, color: "linear-gradient(135deg, #F72585, #7209B7)", fromPrice: 25000, createdAt: new Date() },
  { id: "11", name: "TikTok", slug: "tiktok", icon: "🎵", productCount: 12, color: "linear-gradient(135deg, #000000, #25F4EE)", fromPrice: 250000, createdAt: new Date() },
  { id: "12", name: "Khác", slug: "other", icon: "📦", productCount: 18, color: "linear-gradient(135deg, #64748B, #475569)", fromPrice: 10000, createdAt: new Date() },
];

export const mockServices: Service[] = [
  // Facebook Services
  {
    id: "1",
    name: "Khôi phục mật khẩu",
    slug: "khoi-phuc-mat-khau",
    icon: "🔑",
    description: "Hỗ trợ khôi phục mật khẩu tài khoản Facebook bị quên hoặc mất.",
    price: 50000,
    category: "Facebook",
    createdAt: new Date(),
  },
  {
    id: "2",
    name: "Report tài khoản cá nhân",
    slug: "report-tai-khoan",
    icon: "🚫",
    description: "Report tài khoản Facebook vi phạm, spam, lừa đảo.",
    price: 30000,
    category: "Facebook",
    createdAt: new Date(),
  },
  {
    id: "fb-1",
    name: "Lên tích xanh Facebook - Fanpage",
    slug: "len-tich-xanh-facebook",
    icon: "🛡️",
    description: "Dịch vụ hỗ trợ lên tích xanh cho cá nhân và Fanpage Facebook.",
    price: 5000000,
    category: "Facebook",
    createdAt: new Date(),
  },
  {
    id: "fb-2",
    name: "Lọc bạn bè không tương tác",
    slug: "loc-ban-be",
    icon: "👥",
    description: "Tự động lọc và xóa bạn bè không tương tác trên Facebook.",
    price: 50000,
    category: "Facebook",
    createdAt: new Date(),
  },
  {
    id: "fb-3",
    name: "Kháng page hủy đăng",
    slug: "khang-page-huy-dang",
    icon: "🔓",
    description: "Dịch vụ kháng nghị các Fanpage bị hủy đăng (Unpublished).",
    price: 200000,
    category: "Facebook",
    createdAt: new Date(),
  },

  // Instagram Services
  {
    id: "ig-1",
    name: "Tích xanh Instagram",
    slug: "tich-xanh-instagram",
    icon: "📸",
    description: "Hỗ trợ đăng ký và xác minh tích xanh Instagram chính chủ.",
    price: 4500000,
    category: "Instagram",
    createdAt: new Date(),
  },
  {
    id: "ig-2",
    name: "Mở khóa Instagram",
    slug: "mo-khoa-instagram",
    icon: "🔓",
    description: "Dịch vụ mở khóa tài khoản Instagram bị vô hiệu hóa hoặc bị hack.",
    price: 300000,
    category: "Instagram",
    createdAt: new Date(),
  },

  // TikTok Services
  {
    id: "tt-1",
    name: "Mở khóa TikTok",
    slug: "mo-khoa-tiktok",
    icon: "🎵",
    description: "Dịch vụ mở khóa tài khoản TikTok bị đình chỉ hoặc vi phạm chính sách.",
    price: 500000,
    category: "TikTok",
    createdAt: new Date(),
  },
  {
    id: "tt-2",
    name: "Report TikTok",
    slug: "report-tiktok",
    icon: "🚩",
    description: "Dịch vụ report tài khoản TikTok vi phạm, lừa đảo, giả mạo.",
    price: 100000,
    category: "TikTok",
    createdAt: new Date(),
  },
  {
    id: "tt-3",
    name: "Kháng nghị Livestream",
    slug: "khang-livestream-tiktok",
    icon: "🎥",
    description: "Kháng nghị mở lại tính năng Livestream bị cấm trên TikTok.",
    price: 300000,
    category: "TikTok",
    createdAt: new Date(),
  },

  // Interaction Services
  {
    id: "int-1",
    name: "Tăng Like Facebook",
    slug: "tang-like-facebook",
    icon: "👍",
    description: "Tăng lượt thích cho bài viết cá nhân hoặc Fanpage.",
    price: 100,
    category: "Tương tác",
    createdAt: new Date(),
  },
  {
    id: "int-2",
    name: "Tăng Follow TikTok",
    slug: "tang-follow-tiktok",
    icon: "➕",
    description: "Tăng lượt theo dõi thực cho tài khoản TikTok.",
    price: 200,
    category: "Tương tác",
    createdAt: new Date(),
  },
  {
    id: "int-3",
    name: "Tăng View YouTube",
    slug: "tang-view-youtube",
    icon: "👀",
    description: "Tăng lượt xem an toàn, không tụt cho video YouTube.",
    price: 50,
    category: "Tương tác",
    createdAt: new Date(),
  },
  {
    id: "int-4",
    name: "Tăng Tim Instagram",
    slug: "tang-tim-instagram",
    icon: "❤️",
    description: "Tăng lượt tim cho bài viết Instagram.",
    price: 150,
    category: "Tương tác",
    createdAt: new Date(),
  },

  {
    id: "6",
    name: "Hỗ trợ BM",
    slug: "ho-tro-bm",
    icon: "⚙️",
    description: "Dịch vụ setup, quản lý Business Manager cho Facebook Ads.",
    price: 200000,
    category: "Facebook",
    createdAt: new Date(),
  },
];

export const mockOrders = [
  { id: "DH001", product: "Netflix Premium 1 tháng", price: 49000, status: "SUCCESS", date: "2026-05-18" },
  { id: "DH002", product: "Spotify Premium 1 năm", price: 79000, status: "PROCESSING", date: "2026-05-17" },
  { id: "DH003", product: "Canva Pro 1 năm", price: 39000, status: "SUCCESS", date: "2026-05-16" },
  { id: "DH004", product: "Facebook VIA UID VN", price: 150000, status: "FAILED", date: "2026-05-15" },
];

export const mockTopupHistory = [
  { id: "NAP001", amount: 500000, bank: "Vietcombank", status: "APPROVED", date: "2026-05-18" },
  { id: "NAP002", amount: 200000, bank: "MB Bank", status: "APPROVED", date: "2026-05-15" },
  { id: "NAP003", amount: 1000000, bank: "TPBank", status: "PENDING", date: "2026-05-14" },
];
